#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import os
import struct
import subprocess
import sys

# 与 bootloader 中的 image_header_t 配套
# typedef struct __attribute__((packed)) {
#   uint32_t magic;
#   uint32_t load_addr;
#   uint32_t entry_addr;
#   uint32_t image_size;
#   uint32_t bss_start;
#   uint32_t bss_size;
#   uint32_t stack_top;
#   uint32_t flags;
# } image_header_t;
IMAGE_MAGIC = 0x4D544553  # "MTES"


def run_cmd(cmd):
    try:
        return subprocess.check_output(cmd, text=True)
    except subprocess.CalledProcessError as e:
        print(f"[ERROR] command failed: {' '.join(cmd)}", file=sys.stderr)
        print(e, file=sys.stderr)
        sys.exit(1)
    except FileNotFoundError:
        print(f"[ERROR] tool not found: {cmd[0]}", file=sys.stderr)
        sys.exit(1)


def load_symbols(elf_path, nm_tool):
    out = run_cmd([nm_tool, "-n", elf_path])
    syms = {}
    for line in out.splitlines():
        parts = line.strip().split()
        if len(parts) < 3:
            continue
        addr_str = parts[0]
        name = parts[-1]
        try:
            addr = int(addr_str, 16)
        except ValueError:
            continue
        syms[name] = addr
    return syms


def get_required_symbol(syms, name):
    if name not in syms:
        print(f"[ERROR] missing required symbol: {name}", file=sys.stderr)
        sys.exit(1)
    return syms[name]


def main():
    parser = argparse.ArgumentParser(
        description="Pack ELF+BIN into bootloader-loadable image (header + raw binary)."
    )
    parser.add_argument("elf", help="input ELF file")
    parser.add_argument("bin", help="input raw BIN file generated by objcopy")
    parser.add_argument("out", help="output packed IMG file")
    parser.add_argument("--nm", default=os.environ.get("NM", "riscv64-linux-gnu-nm"),
                        help="nm tool path")
    parser.add_argument("--magic", default=f"0x{IMAGE_MAGIC:08x}",
                        help="image magic, default: 0x4D544553")
    parser.add_argument("--flags", default="0",
                        help="optional flags field, default: 0")
    parser.add_argument("--strict-size-check", action="store_true",
                        help="if set, require _image_size == len(bin)")
    args = parser.parse_args()

    elf_path = os.path.abspath(args.elf)
    bin_path = os.path.abspath(args.bin)
    out_path = os.path.abspath(args.out)

    if not os.path.isfile(elf_path):
        print(f"[ERROR] ELF not found: {elf_path}", file=sys.stderr)
        sys.exit(1)
    if not os.path.isfile(bin_path):
        print(f"[ERROR] BIN not found: {bin_path}", file=sys.stderr)
        sys.exit(1)

    try:
        magic = int(args.magic, 0) & 0xFFFFFFFF
        flags = int(args.flags, 0) & 0xFFFFFFFF
    except ValueError:
        print("[ERROR] --magic / --flags must be valid integers", file=sys.stderr)
        sys.exit(1)

    syms = load_symbols(elf_path, args.nm)

    # 这些符号由你前面那几份 ld 提供
    load_addr = get_required_symbol(syms, "_image_start") & 0xFFFFFFFF
    entry_addr = get_required_symbol(syms, "_start") & 0xFFFFFFFF
    bss_start = get_required_symbol(syms, "_bss_start") & 0xFFFFFFFF
    bss_end = get_required_symbol(syms, "_bss_end") & 0xFFFFFFFF
    stack_top = get_required_symbol(syms, "_stack_top") & 0xFFFFFFFF

    with open(bin_path, "rb") as f:
        bin_data = f.read()

    image_size = len(bin_data) & 0xFFFFFFFF
    bss_size = (bss_end - bss_start) & 0xFFFFFFFF

    # 如果链接脚本里提供了 _image_size / _image_load_end，就做一致性检查
    image_size_sym = syms.get("_image_size", None)
    image_load_end_sym = syms.get("_image_load_end", None)

    if image_size_sym is not None:
        image_size_ld = image_size_sym & 0xFFFFFFFF
        if image_size_ld != image_size:
            msg = (f"[WARN] _image_size (0x{image_size_ld:08X}) != "
                   f"len(bin) (0x{image_size:08X})")
            if args.strict_size_check:
                print(msg, file=sys.stderr)
                sys.exit(1)
            else:
                print(msg)

    if image_load_end_sym is not None:
        calc = ((image_load_end_sym & 0xFFFFFFFF) - load_addr) & 0xFFFFFFFF
        if calc != image_size:
            msg = (f"[WARN] (_image_load_end - _image_start)=0x{calc:08X} != "
                   f"len(bin)=0x{image_size:08X}")
            if args.strict_size_check:
                print(msg, file=sys.stderr)
                sys.exit(1)
            else:
                print(msg)

    if bss_end < bss_start:
        print("[ERROR] _bss_end < _bss_start", file=sys.stderr)
        sys.exit(1)

    # header = 8 x uint32_t, little-endian
    header = struct.pack(
        "<8I",
        magic,
        load_addr,
        entry_addr,
        image_size,
        bss_start,
        bss_size,
        stack_top,
        flags,
    )

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "wb") as f:
        f.write(header)
        f.write(bin_data)

    print(f"[PACK] generated: {out_path}")
    print(f"  magic      = 0x{magic:08X}")
    print(f"  load_addr  = 0x{load_addr:08X}")
    print(f"  entry_addr = 0x{entry_addr:08X}")
    print(f"  image_size = 0x{image_size:08X}")
    print(f"  bss_start  = 0x{bss_start:08X}")
    print(f"  bss_size   = 0x{bss_size:08X}")
    print(f"  stack_top  = 0x{stack_top:08X}")
    print(f"  flags      = 0x{flags:08X}")
    print(f"  total_img  = 0x{(len(header) + len(bin_data)):08X}")


if __name__ == "__main__":
    main()